# Based on https://github.com/doublify/pre-commit-rust
#
# To install pre-commit hooks:
# - install pre-commit; e.g. for MacOS with brew: brew install pre-commit
# - run: pre-commit install

repos:

    - repo: local
      hooks:


          - id: cargo-fmt
            name: "all:  cargo fmt"
            entry: cargo fmt
            language: system
            files: \.rs$
            pass_filenames: false

          - id: cargo-check-util
            name: "util: cargo check"
            entry: cd icon_generator && cargo check
            language: system
            files: \.rs$
            pass_filenames: false

          - id: cargo-check-no-features-lib
            name: "lib:  cargo check --release --bins --lib --examples"
            entry: cd nrf52833_rgb_led_matrix && cargo check --release --bins --lib --examples
            language: system
            files: \.rs$
            pass_filenames: false

          - id: cargo-check-with-features-lib
            name: "lib:  cargo check --release --bins --lib --examples --all-features"
            entry: cd nrf52833_rgb_led_matrix && cargo check --release --bins --lib --examples --all-features
            language: system
            files: \.rs$
            pass_filenames: false