# Based on https://github.com/doublify/pre-commit-rust
#
# To install pre-commit hooks:
# - install pre-commit; e.g. for MacOS with brew: brew install pre-commit
# - run: pre-commit install

repos:

    - repo: local
      hooks:

          - id: cargo-fmt
            name: cargo fmt
            entry: cargo fmt
            language: system
            files: \.rs$
            pass_filenames: false

          - id: cargo-check-no-features
            name: cargo check --release --bins --lib --examples
            entry: cargo check --release --bins --lib --examples
            language: system
            files: \.rs$
            pass_filenames: false

          - id: cargo-check-with-features
            name: cargo check --release --bins --lib --examples --all-features
            entry: cargo check --release --bins --lib --examples --all-features
            language: system
            files: \.rs$
            pass_filenames: false